name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., v1.1.0)'
        required: true
        type: string
      sha256_amd64:
        description: 'SHA256 for AMD64 binary'
        required: true
        type: string
      sha256_arm64:
        description: 'SHA256 for ARM64 binary'
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Update formula
      run: |
        VERSION="${{ github.event.inputs.version || github.event.client_payload.version }}"
        SHA256_AMD64="${{ github.event.inputs.sha256_amd64 || github.event.client_payload.sha256_amd64 }}"
        SHA256_ARM64="${{ github.event.inputs.sha256_arm64 || github.event.client_payload.sha256_arm64 }}"
        
        # Remove 'v' prefix if present
        VERSION_CLEAN=${VERSION#v}
        
        # Update the formula
        cat > Formula/pivot.rb << EOF
        class Pivot < Formula
          desc "GitHub Issues Management CLI"
          homepage "https://github.com/rhino11/pivot"
          version "${VERSION_CLEAN}"
          
          if Hardware::CPU.arm?
            url "https://github.com/rhino11/pivot/releases/download/${VERSION}/pivot-darwin-arm64"
            sha256 "${SHA256_ARM64}"
          else
            url "https://github.com/rhino11/pivot/releases/download/${VERSION}/pivot-darwin-amd64"
            sha256 "${SHA256_AMD64}"
          end
          
          def install
            bin.install Dir["pivot-darwin-*"].first => "pivot"
          end
          
          test do
            assert_match "pivot", shell_output("#{bin}/pivot version")
          end
        end
        EOF
    
    - name: Commit and push
      run: |
        VERSION="${{ github.event.inputs.version || github.event.client_payload.version }}"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/pivot.rb
        git commit -m "Update pivot to ${VERSION}" || exit 0
        git push
